#!/bin/sh

BASE=/etc/php/8.0
MODS=$BASE/mods-available
CONF=$BASE/cli/conf.d

if [ \( "${PHP_MODULES_ALL:-1}" != 0 -a -z "${PHP_CLI_MODULES_ALL}" \) -o \( "${PHP_CLI_MODULES_ALL}" != 0 -a -n "${PHP_CLI_MODULES_ALL}" \) ]; then
	[ \( "${PHP_MODULE_IMAGICK:-1}" = 0 -a -z "${PHP_CLI_MODULE_IMAGICK}" \) -o "${PHP_CLI_MODULE_IMAGICK:-1}" = 0 ] || PHP_CLI_MODULE_GMAGICK=0

	[ \( "${PHP_MODULE_AMQP:-1}" = 0 -a -z "${PHP_CLI_MODULE_AMQP}" \) -o "${PHP_CLI_MODULE_AMQP:-1}" = 0 ] && rm -f $CONF/20-amqp.ini || ln -sf $MODS/amqp.ini $CONF/20-amqp.ini
	[ \( "${PHP_MODULE_APCU:-1}" = 0 -a -z "${PHP_CLI_MODULE_APCU}" \) -o "${PHP_CLI_MODULE_APCU:-1}" = 0 ] && rm -f $CONF/20-apcu.ini || ln -sf $MODS/apcu.ini $CONF/20-apcu.ini
	[ \( "${PHP_MODULE_AST:-1}" = 0 -a -z "${PHP_CLI_MODULE_AST}" \) -o "${PHP_CLI_MODULE_AST:-1}" = 0 ] && rm -f $CONF/20-ast.ini || ln -sf $MODS/ast.ini $CONF/20-ast.ini
	[ \( "${PHP_MODULE_BCMATH:-1}" = 0 -a -z "${PHP_CLI_MODULE_BCMATH}" \) -o "${PHP_CLI_MODULE_BCMATH:-1}" = 0 ] && rm -f $CONF/20-bcmath.ini || ln -sf $MODS/bcmath.ini $CONF/20-bcmath.ini
	[ \( "${PHP_MODULE_BZ2:-1}" = 0 -a -z "${PHP_CLI_MODULE_BZ2}" \) -o "${PHP_CLI_MODULE_BZ2:-1}" = 0 ] && rm -f $CONF/20-bz2.ini || ln -sf $MODS/bz2.ini $CONF/20-bz2.ini
	[ \( "${PHP_MODULE_CALENDAR:-1}" = 0 -a -z "${PHP_CLI_MODULE_CALENDAR}" \) -o "${PHP_CLI_MODULE_CALENDAR:-1}" = 0 ] && rm -f $CONF/20-calendar.ini || ln -sf $MODS/calendar.ini $CONF/20-calendar.ini
	[ \( "${PHP_MODULE_CTYPE:-1}" = 0 -a -z "${PHP_CLI_MODULE_CTYPE}" \) -o "${PHP_CLI_MODULE_CTYPE:-1}" = 0 ] && rm -f $CONF/20-ctype.ini || ln -sf $MODS/ctype.ini $CONF/20-ctype.ini
	[ \( "${PHP_MODULE_CURL:-1}" = 0 -a -z "${PHP_CLI_MODULE_CURL}" \) -o "${PHP_CLI_MODULE_CURL:-1}" = 0 ] && rm -f $CONF/20-curl.ini || ln -sf $MODS/curl.ini $CONF/20-curl.ini
	[ \( "${PHP_MODULE_DBA:-1}" = 0 -a -z "${PHP_CLI_MODULE_DBA}" \) -o "${PHP_CLI_MODULE_DBA:-1}" = 0 ] && rm -f $CONF/20-dba.ini || ln -sf $MODS/dba.ini $CONF/20-dba.ini
	[ \( "${PHP_MODULE_DECIMAL:-1}" = 0 -a -z "${PHP_CLI_MODULE_DECIMAL}" \) -o "${PHP_CLI_MODULE_DECIMAL:-1}" = 0 ] && rm -f $CONF/30-decimal.ini || ln -sf $MODS/decimal.ini $CONF/30-decimal.ini
	[ \( "${PHP_MODULE_DIO:-1}" = 0 -a -z "${PHP_CLI_MODULE_DIO}" \) -o "${PHP_CLI_MODULE_DIO:-1}" = 0 ] && rm -f $CONF/20-dio.ini || ln -sf $MODS/dio.ini $CONF/20-dio.ini
	[ \( "${PHP_MODULE_DOM:-1}" = 0 -a -z "${PHP_CLI_MODULE_DOM}" \) -o "${PHP_CLI_MODULE_DOM:-1}" = 0 ] && rm -f $CONF/20-dom.ini || ln -sf $MODS/dom.ini $CONF/20-dom.ini
	[ \( "${PHP_MODULE_DS:-1}" = 0 -a -z "${PHP_CLI_MODULE_DS}" \) -o "${PHP_CLI_MODULE_DS:-1}" = 0 ] && rm -f $CONF/30-ds.ini || ln -sf $MODS/ds.ini $CONF/30-ds.ini
	[ \( "${PHP_MODULE_ENCHANT:-1}" = 0 -a -z "${PHP_CLI_MODULE_ENCHANT}" \) -o "${PHP_CLI_MODULE_ENCHANT:-1}" = 0 ] && rm -f $CONF/20-enchant.ini || ln -sf $MODS/enchant.ini $CONF/20-enchant.ini
	[ \( "${PHP_MODULE_EXCIMER:-1}" = 0 -a -z "${PHP_CLI_MODULE_EXCIMER}" \) -o "${PHP_CLI_MODULE_EXCIMER:-1}" = 0 ] && rm -f $CONF/20-excimer.ini || ln -sf $MODS/excimer.ini $CONF/20-excimer.ini
	[ \( "${PHP_MODULE_EXIF:-1}" = 0 -a -z "${PHP_CLI_MODULE_EXIF}" \) -o "${PHP_CLI_MODULE_EXIF:-1}" = 0 ] && rm -f $CONF/20-exif.ini || ln -sf $MODS/exif.ini $CONF/20-exif.ini
	[ \( "${PHP_MODULE_FFI:-1}" = 0 -a -z "${PHP_CLI_MODULE_FFI}" \) -o "${PHP_CLI_MODULE_FFI:-1}" = 0 ] && rm -f $CONF/20-ffi.ini || ln -sf $MODS/ffi.ini $CONF/20-ffi.ini
	[ \( "${PHP_MODULE_FILEINFO:-1}" = 0 -a -z "${PHP_CLI_MODULE_FILEINFO}" \) -o "${PHP_CLI_MODULE_FILEINFO:-1}" = 0 ] && rm -f $CONF/20-fileinfo.ini || ln -sf $MODS/fileinfo.ini $CONF/20-fileinfo.ini
	[ \( "${PHP_MODULE_FTP:-1}" = 0 -a -z "${PHP_CLI_MODULE_FTP}" \) -o "${PHP_CLI_MODULE_FTP:-1}" = 0 ] && rm -f $CONF/20-ftp.ini || ln -sf $MODS/ftp.ini $CONF/20-ftp.ini
	[ \( "${PHP_MODULE_GD:-1}" = 0 -a -z "${PHP_CLI_MODULE_GD}" \) -o "${PHP_CLI_MODULE_GD:-1}" = 0 ] && rm -f $CONF/20-gd.ini || ln -sf $MODS/gd.ini $CONF/20-gd.ini
	[ \( "${PHP_MODULE_GEARMAN:-1}" = 0 -a -z "${PHP_CLI_MODULE_GEARMAN}" \) -o "${PHP_CLI_MODULE_GEARMAN:-1}" = 0 ] && rm -f $CONF/20-gearman.ini || ln -sf $MODS/gearman.ini $CONF/20-gearman.ini
	[ \( "${PHP_MODULE_GETTEXT:-1}" = 0 -a -z "${PHP_CLI_MODULE_GETTEXT}" \) -o "${PHP_CLI_MODULE_GETTEXT:-1}" = 0 ] && rm -f $CONF/20-gettext.ini || ln -sf $MODS/gettext.ini $CONF/20-gettext.ini
	[ \( "${PHP_MODULE_GMAGICK:-1}" = 0 -a -z "${PHP_CLI_MODULE_GMAGICK}" \) -o "${PHP_CLI_MODULE_GMAGICK:-1}" = 0 ] && rm -f $CONF/20-gmagick.ini || ln -sf $MODS/gmagick.ini $CONF/20-gmagick.ini
	[ \( "${PHP_MODULE_GMP:-1}" = 0 -a -z "${PHP_CLI_MODULE_GMP}" \) -o "${PHP_CLI_MODULE_GMP:-1}" = 0 ] && rm -f $CONF/20-gmp.ini || ln -sf $MODS/gmp.ini $CONF/20-gmp.ini
	[ \( "${PHP_MODULE_GNUPG:-1}" = 0 -a -z "${PHP_CLI_MODULE_GNUPG}" \) -o "${PHP_CLI_MODULE_GNUPG:-1}" = 0 ] && rm -f $CONF/20-gnupg.ini || ln -sf $MODS/gnupg.ini $CONF/20-gnupg.ini
	[ \( "${PHP_MODULE_GRPC:-1}" = 0 -a -z "${PHP_CLI_MODULE_GRPC}" \) -o "${PHP_CLI_MODULE_GRPC:-1}" = 0 ] && rm -f $CONF/30-grpc.ini || ln -sf $MODS/grpc.ini $CONF/30-grpc.ini
	[ \( "${PHP_MODULE_HTTP:-1}" = 0 -a -z "${PHP_CLI_MODULE_HTTP}" \) -o "${PHP_CLI_MODULE_HTTP:-1}" = 0 ] && rm -f $CONF/25-http.ini || ln -sf $MODS/http.ini $CONF/25-http.ini
	[ \( "${PHP_MODULE_ICONV:-1}" = 0 -a -z "${PHP_CLI_MODULE_ICONV}" \) -o "${PHP_CLI_MODULE_ICONV:-1}" = 0 ] && rm -f $CONF/20-iconv.ini || ln -sf $MODS/iconv.ini $CONF/20-iconv.ini
	[ \( "${PHP_MODULE_IGBINARY:-1}" = 0 -a -z "${PHP_CLI_MODULE_IGBINARY}" \) -o "${PHP_CLI_MODULE_IGBINARY:-1}" = 0 ] && rm -f $CONF/20-igbinary.ini || ln -sf $MODS/igbinary.ini $CONF/20-igbinary.ini
	[ \( "${PHP_MODULE_IMAGICK:-1}" = 0 -a -z "${PHP_CLI_MODULE_IMAGICK}" \) -o "${PHP_CLI_MODULE_IMAGICK:-1}" = 0 ] && rm -f $CONF/20-imagick.ini || ln -sf $MODS/imagick.ini $CONF/20-imagick.ini
	[ \( "${PHP_MODULE_IMAP:-1}" = 0 -a -z "${PHP_CLI_MODULE_IMAP}" \) -o "${PHP_CLI_MODULE_IMAP:-1}" = 0 ] && rm -f $CONF/20-imap.ini || ln -sf $MODS/imap.ini $CONF/20-imap.ini
	[ \( "${PHP_MODULE_INOTIFY:-1}" = 0 -a -z "${PHP_CLI_MODULE_INOTIFY}" \) -o "${PHP_CLI_MODULE_INOTIFY:-1}" = 0 ] && rm -f $CONF/30-inotify.ini || ln -sf $MODS/inotify.ini $CONF/30-inotify.ini
	[ \( "${PHP_MODULE_INTL:-1}" = 0 -a -z "${PHP_CLI_MODULE_INTL}" \) -o "${PHP_CLI_MODULE_INTL:-1}" = 0 ] && rm -f $CONF/20-intl.ini || ln -sf $MODS/intl.ini $CONF/20-intl.ini
	[ \( "${PHP_MODULE_LDAP:-1}" = 0 -a -z "${PHP_CLI_MODULE_LDAP}" \) -o "${PHP_CLI_MODULE_LDAP:-1}" = 0 ] && rm -f $CONF/20-ldap.ini || ln -sf $MODS/ldap.ini $CONF/20-ldap.ini
	[ \( "${PHP_MODULE_LIBVIRT_PHP:-1}" = 0 -a -z "${PHP_CLI_MODULE_LIBVIRT_PHP}" \) -o "${PHP_CLI_MODULE_LIBVIRT_PHP:-1}" = 0 ] && rm -f $CONF/40-libvirt-php.ini || ln -sf $MODS/libvirt-php.ini $CONF/40-libvirt-php.ini
	[ \( "${PHP_MODULE_LZ4:-1}" = 0 -a -z "${PHP_CLI_MODULE_LZ4}" \) -o "${PHP_CLI_MODULE_LZ4:-1}" = 0 ] && rm -f $CONF/20-lz4.ini || ln -sf $MODS/lz4.ini $CONF/20-lz4.ini
	[ \( "${PHP_MODULE_MAILPARSE:-1}" = 0 -a -z "${PHP_CLI_MODULE_MAILPARSE}" \) -o "${PHP_CLI_MODULE_MAILPARSE:-1}" = 0 ] && rm -f $CONF/25-mailparse.ini || ln -sf $MODS/mailparse.ini $CONF/25-mailparse.ini
	[ \( "${PHP_MODULE_MAXMINDDB:-1}" = 0 -a -z "${PHP_CLI_MODULE_MAXMINDDB}" \) -o "${PHP_CLI_MODULE_MAXMINDDB:-1}" = 0 ] && rm -f $CONF/30-maxminddb.ini || ln -sf $MODS/maxminddb.ini $CONF/30-maxminddb.ini
	[ \( "${PHP_MODULE_MBSTRING:-1}" = 0 -a -z "${PHP_CLI_MODULE_MBSTRING}" \) -o "${PHP_CLI_MODULE_MBSTRING:-1}" = 0 ] && rm -f $CONF/20-mbstring.ini || ln -sf $MODS/mbstring.ini $CONF/20-mbstring.ini
	[ \( "${PHP_MODULE_MCRYPT:-1}" = 0 -a -z "${PHP_CLI_MODULE_MCRYPT}" \) -o "${PHP_CLI_MODULE_MCRYPT:-1}" = 0 ] && rm -f $CONF/20-mcrypt.ini || ln -sf $MODS/mcrypt.ini $CONF/20-mcrypt.ini
	[ \( "${PHP_MODULE_MEMCACHE:-1}" = 0 -a -z "${PHP_CLI_MODULE_MEMCACHE}" \) -o "${PHP_CLI_MODULE_MEMCACHE:-1}" = 0 ] && rm -f $CONF/20-memcache.ini || ln -sf $MODS/memcache.ini $CONF/20-memcache.ini
	[ \( "${PHP_MODULE_MEMCACHED:-1}" = 0 -a -z "${PHP_CLI_MODULE_MEMCACHED}" \) -o "${PHP_CLI_MODULE_MEMCACHED:-1}" = 0 ] && rm -f $CONF/25-memcached.ini || ln -sf $MODS/memcached.ini $CONF/25-memcached.ini
	[ \( "${PHP_MODULE_MONGODB:-1}" = 0 -a -z "${PHP_CLI_MODULE_MONGODB}" \) -o "${PHP_CLI_MODULE_MONGODB:-1}" = 0 ] && rm -f $CONF/20-mongodb.ini || ln -sf $MODS/mongodb.ini $CONF/20-mongodb.ini
	[ \( "${PHP_MODULE_MSGPACK:-1}" = 0 -a -z "${PHP_CLI_MODULE_MSGPACK}" \) -o "${PHP_CLI_MODULE_MSGPACK:-1}" = 0 ] && rm -f $CONF/20-msgpack.ini || ln -sf $MODS/msgpack.ini $CONF/20-msgpack.ini
	[ \( "${PHP_MODULE_MYSQLI:-1}" = 0 -a -z "${PHP_CLI_MODULE_MYSQLI}" \) -o "${PHP_CLI_MODULE_MYSQLI:-1}" = 0 ] && rm -f $CONF/20-mysqli.ini || ln -sf $MODS/mysqli.ini $CONF/20-mysqli.ini
	[ \( "${PHP_MODULE_MYSQLND:-1}" = 0 -a -z "${PHP_CLI_MODULE_MYSQLND}" \) -o "${PHP_CLI_MODULE_MYSQLND:-1}" = 0 ] && rm -f $CONF/10-mysqlnd.ini || ln -sf $MODS/mysqlnd.ini $CONF/10-mysqlnd.ini
	[ \( "${PHP_MODULE_OAUTH:-1}" = 0 -a -z "${PHP_CLI_MODULE_OAUTH}" \) -o "${PHP_CLI_MODULE_OAUTH:-1}" = 0 ] && rm -f $CONF/20-oauth.ini || ln -sf $MODS/oauth.ini $CONF/20-oauth.ini
	[ \( "${PHP_MODULE_ODBC:-1}" = 0 -a -z "${PHP_CLI_MODULE_ODBC}" \) -o "${PHP_CLI_MODULE_ODBC:-1}" = 0 ] && rm -f $CONF/20-odbc.ini || ln -sf $MODS/odbc.ini $CONF/20-odbc.ini
	[ \( "${PHP_MODULE_OPCACHE:-1}" = 0 -a -z "${PHP_CLI_MODULE_OPCACHE}" \) -o "${PHP_CLI_MODULE_OPCACHE:-1}" = 0 ] && rm -f $CONF/10-opcache.ini || ln -sf $MODS/opcache.ini $CONF/10-opcache.ini
	[ \( "${PHP_MODULE_OPENTELEMETRY:-1}" = 0 -a -z "${PHP_CLI_MODULE_OPENTELEMETRY}" \) -o "${PHP_CLI_MODULE_OPENTELEMETRY:-1}" = 0 ] && rm -f $CONF/20-opentelemetry.ini || ln -sf $MODS/opentelemetry.ini $CONF/20-opentelemetry.ini
	[ \( "${PHP_MODULE_PCOV:-1}" = 0 -a -z "${PHP_CLI_MODULE_PCOV}" \) -o "${PHP_CLI_MODULE_PCOV:-1}" = 0 ] && rm -f $CONF/20-pcov.ini || ln -sf $MODS/pcov.ini $CONF/20-pcov.ini
	[ \( "${PHP_MODULE_PDO:-1}" = 0 -a -z "${PHP_CLI_MODULE_PDO}" \) -o "${PHP_CLI_MODULE_PDO:-1}" = 0 ] && rm -f $CONF/10-pdo.ini || ln -sf $MODS/pdo.ini $CONF/10-pdo.ini
	[ \( "${PHP_MODULE_PDO_DBLIB:-1}" = 0 -a -z "${PHP_CLI_MODULE_PDO_DBLIB}" \) -o "${PHP_CLI_MODULE_PDO_DBLIB:-1}" = 0 ] && rm -f $CONF/20-pdo_dblib.ini || ln -sf $MODS/pdo_dblib.ini $CONF/20-pdo_dblib.ini
	[ \( "${PHP_MODULE_PDO_FIREBIRD:-1}" = 0 -a -z "${PHP_CLI_MODULE_PDO_FIREBIRD}" \) -o "${PHP_CLI_MODULE_PDO_FIREBIRD:-1}" = 0 ] && rm -f $CONF/20-pdo_firebird.ini || ln -sf $MODS/pdo_firebird.ini $CONF/20-pdo_firebird.ini
	[ \( "${PHP_MODULE_PDO_MYSQL:-1}" = 0 -a -z "${PHP_CLI_MODULE_PDO_MYSQL}" \) -o "${PHP_CLI_MODULE_PDO_MYSQL:-1}" = 0 ] && rm -f $CONF/20-pdo_mysql.ini || ln -sf $MODS/pdo_mysql.ini $CONF/20-pdo_mysql.ini
	[ \( "${PHP_MODULE_PDO_ODBC:-1}" = 0 -a -z "${PHP_CLI_MODULE_PDO_ODBC}" \) -o "${PHP_CLI_MODULE_PDO_ODBC:-1}" = 0 ] && rm -f $CONF/20-pdo_odbc.ini || ln -sf $MODS/pdo_odbc.ini $CONF/20-pdo_odbc.ini
	[ \( "${PHP_MODULE_PDO_PGSQL:-1}" = 0 -a -z "${PHP_CLI_MODULE_PDO_PGSQL}" \) -o "${PHP_CLI_MODULE_PDO_PGSQL:-1}" = 0 ] && rm -f $CONF/20-pdo_pgsql.ini || ln -sf $MODS/pdo_pgsql.ini $CONF/20-pdo_pgsql.ini
	[ \( "${PHP_MODULE_PDO_SQLITE:-1}" = 0 -a -z "${PHP_CLI_MODULE_PDO_SQLITE}" \) -o "${PHP_CLI_MODULE_PDO_SQLITE:-1}" = 0 ] && rm -f $CONF/20-pdo_sqlite.ini || ln -sf $MODS/pdo_sqlite.ini $CONF/20-pdo_sqlite.ini
	[ \( "${PHP_MODULE_PGSQL:-1}" = 0 -a -z "${PHP_CLI_MODULE_PGSQL}" \) -o "${PHP_CLI_MODULE_PGSQL:-1}" = 0 ] && rm -f $CONF/20-pgsql.ini || ln -sf $MODS/pgsql.ini $CONF/20-pgsql.ini
	[ \( "${PHP_MODULE_PHALCON:-1}" = 0 -a -z "${PHP_CLI_MODULE_PHALCON}" \) -o "${PHP_CLI_MODULE_PHALCON:-1}" = 0 ] && rm -f $CONF/35-phalcon.ini || ln -sf $MODS/phalcon.ini $CONF/35-phalcon.ini
	[ \( "${PHP_MODULE_PHAR:-1}" = 0 -a -z "${PHP_CLI_MODULE_PHAR}" \) -o "${PHP_CLI_MODULE_PHAR:-1}" = 0 ] && rm -f $CONF/20-phar.ini || ln -sf $MODS/phar.ini $CONF/20-phar.ini
	[ \( "${PHP_MODULE_PINBA:-1}" = 0 -a -z "${PHP_CLI_MODULE_PINBA}" \) -o "${PHP_CLI_MODULE_PINBA:-1}" = 0 ] && rm -f $CONF/20-pinba.ini || ln -sf $MODS/pinba.ini $CONF/20-pinba.ini
	[ \( "${PHP_MODULE_POSIX:-1}" = 0 -a -z "${PHP_CLI_MODULE_POSIX}" \) -o "${PHP_CLI_MODULE_POSIX:-1}" = 0 ] && rm -f $CONF/20-posix.ini || ln -sf $MODS/posix.ini $CONF/20-posix.ini
	[ \( "${PHP_MODULE_PQ:-1}" = 0 -a -z "${PHP_CLI_MODULE_PQ}" \) -o "${PHP_CLI_MODULE_PQ:-1}" = 0 ] && rm -f $CONF/25-pq.ini || ln -sf $MODS/pq.ini $CONF/25-pq.ini
	[ \( "${PHP_MODULE_PROPRO:-1}" = 0 -a -z "${PHP_CLI_MODULE_PROPRO}" \) -o "${PHP_CLI_MODULE_PROPRO:-1}" = 0 ] && rm -f $CONF/20-propro.ini || ln -sf $MODS/propro.ini $CONF/20-propro.ini
	[ \( "${PHP_MODULE_PROTOBUF:-1}" = 0 -a -z "${PHP_CLI_MODULE_PROTOBUF}" \) -o "${PHP_CLI_MODULE_PROTOBUF:-1}" = 0 ] && rm -f $CONF/30-protobuf.ini || ln -sf $MODS/protobuf.ini $CONF/30-protobuf.ini
	[ \( "${PHP_MODULE_PS:-1}" = 0 -a -z "${PHP_CLI_MODULE_PS}" \) -o "${PHP_CLI_MODULE_PS:-1}" = 0 ] && rm -f $CONF/20-ps.ini || ln -sf $MODS/ps.ini $CONF/20-ps.ini
	[ \( "${PHP_MODULE_PSPELL:-1}" = 0 -a -z "${PHP_CLI_MODULE_PSPELL}" \) -o "${PHP_CLI_MODULE_PSPELL:-1}" = 0 ] && rm -f $CONF/20-pspell.ini || ln -sf $MODS/pspell.ini $CONF/20-pspell.ini
	[ \( "${PHP_MODULE_PSR:-1}" = 0 -a -z "${PHP_CLI_MODULE_PSR}" \) -o "${PHP_CLI_MODULE_PSR:-1}" = 0 ] && rm -f $CONF/15-psr.ini || ln -sf $MODS/psr.ini $CONF/15-psr.ini
	[ \( "${PHP_MODULE_RAPHF:-1}" = 0 -a -z "${PHP_CLI_MODULE_RAPHF}" \) -o "${PHP_CLI_MODULE_RAPHF:-1}" = 0 ] && rm -f $CONF/20-raphf.ini || ln -sf $MODS/raphf.ini $CONF/20-raphf.ini
	[ \( "${PHP_MODULE_RDKAFKA:-1}" = 0 -a -z "${PHP_CLI_MODULE_RDKAFKA}" \) -o "${PHP_CLI_MODULE_RDKAFKA:-1}" = 0 ] && rm -f $CONF/30-rdkafka.ini || ln -sf $MODS/rdkafka.ini $CONF/30-rdkafka.ini
	[ \( "${PHP_MODULE_READLINE:-1}" = 0 -a -z "${PHP_CLI_MODULE_READLINE}" \) -o "${PHP_CLI_MODULE_READLINE:-1}" = 0 ] && rm -f $CONF/20-readline.ini || ln -sf $MODS/readline.ini $CONF/20-readline.ini
	[ \( "${PHP_MODULE_REDIS:-1}" = 0 -a -z "${PHP_CLI_MODULE_REDIS}" \) -o "${PHP_CLI_MODULE_REDIS:-1}" = 0 ] && rm -f $CONF/25-redis.ini || ln -sf $MODS/redis.ini $CONF/25-redis.ini
	[ \( "${PHP_MODULE_RRD:-1}" = 0 -a -z "${PHP_CLI_MODULE_RRD}" \) -o "${PHP_CLI_MODULE_RRD:-1}" = 0 ] && rm -f $CONF/20-rrd.ini || ln -sf $MODS/rrd.ini $CONF/20-rrd.ini
	[ \( "${PHP_MODULE_SHMOP:-1}" = 0 -a -z "${PHP_CLI_MODULE_SHMOP}" \) -o "${PHP_CLI_MODULE_SHMOP:-1}" = 0 ] && rm -f $CONF/20-shmop.ini || ln -sf $MODS/shmop.ini $CONF/20-shmop.ini
	[ \( "${PHP_MODULE_SIMPLEXML:-1}" = 0 -a -z "${PHP_CLI_MODULE_SIMPLEXML}" \) -o "${PHP_CLI_MODULE_SIMPLEXML:-1}" = 0 ] && rm -f $CONF/20-simplexml.ini || ln -sf $MODS/simplexml.ini $CONF/20-simplexml.ini
	[ \( "${PHP_MODULE_SMBCLIENT:-1}" = 0 -a -z "${PHP_CLI_MODULE_SMBCLIENT}" \) -o "${PHP_CLI_MODULE_SMBCLIENT:-1}" = 0 ] && rm -f $CONF/20-smbclient.ini || ln -sf $MODS/smbclient.ini $CONF/20-smbclient.ini
	[ \( "${PHP_MODULE_SNMP:-1}" = 0 -a -z "${PHP_CLI_MODULE_SNMP}" \) -o "${PHP_CLI_MODULE_SNMP:-1}" = 0 ] && rm -f $CONF/20-snmp.ini || ln -sf $MODS/snmp.ini $CONF/20-snmp.ini
	[ \( "${PHP_MODULE_SOAP:-1}" = 0 -a -z "${PHP_CLI_MODULE_SOAP}" \) -o "${PHP_CLI_MODULE_SOAP:-1}" = 0 ] && rm -f $CONF/20-soap.ini || ln -sf $MODS/soap.ini $CONF/20-soap.ini
	[ \( "${PHP_MODULE_SOCKETS:-1}" = 0 -a -z "${PHP_CLI_MODULE_SOCKETS}" \) -o "${PHP_CLI_MODULE_SOCKETS:-1}" = 0 ] && rm -f $CONF/20-sockets.ini || ln -sf $MODS/sockets.ini $CONF/20-sockets.ini
	[ \( "${PHP_MODULE_SOLR:-1}" = 0 -a -z "${PHP_CLI_MODULE_SOLR}" \) -o "${PHP_CLI_MODULE_SOLR:-1}" = 0 ] && rm -f $CONF/20-solr.ini || ln -sf $MODS/solr.ini $CONF/20-solr.ini
	[ \( "${PHP_MODULE_SQLITE3:-1}" = 0 -a -z "${PHP_CLI_MODULE_SQLITE3}" \) -o "${PHP_CLI_MODULE_SQLITE3:-1}" = 0 ] && rm -f $CONF/20-sqlite3.ini || ln -sf $MODS/sqlite3.ini $CONF/20-sqlite3.ini
	[ \( "${PHP_MODULE_SSH2:-1}" = 0 -a -z "${PHP_CLI_MODULE_SSH2}" \) -o "${PHP_CLI_MODULE_SSH2:-1}" = 0 ] && rm -f $CONF/20-ssh2.ini || ln -sf $MODS/ssh2.ini $CONF/20-ssh2.ini
	[ \( "${PHP_MODULE_STOMP:-1}" = 0 -a -z "${PHP_CLI_MODULE_STOMP}" \) -o "${PHP_CLI_MODULE_STOMP:-1}" = 0 ] && rm -f $CONF/20-stomp.ini || ln -sf $MODS/stomp.ini $CONF/20-stomp.ini
	[ \( "${PHP_MODULE_SWOOLE:-1}" = 0 -a -z "${PHP_CLI_MODULE_SWOOLE}" \) -o "${PHP_CLI_MODULE_SWOOLE:-1}" = 0 ] && rm -f $CONF/25-swoole.ini || ln -sf $MODS/swoole.ini $CONF/25-swoole.ini
	[ \( "${PHP_MODULE_SYSVMSG:-1}" = 0 -a -z "${PHP_CLI_MODULE_SYSVMSG}" \) -o "${PHP_CLI_MODULE_SYSVMSG:-1}" = 0 ] && rm -f $CONF/20-sysvmsg.ini || ln -sf $MODS/sysvmsg.ini $CONF/20-sysvmsg.ini
	[ \( "${PHP_MODULE_SYSVSEM:-1}" = 0 -a -z "${PHP_CLI_MODULE_SYSVSEM}" \) -o "${PHP_CLI_MODULE_SYSVSEM:-1}" = 0 ] && rm -f $CONF/20-sysvsem.ini || ln -sf $MODS/sysvsem.ini $CONF/20-sysvsem.ini
	[ \( "${PHP_MODULE_SYSVSHM:-1}" = 0 -a -z "${PHP_CLI_MODULE_SYSVSHM}" \) -o "${PHP_CLI_MODULE_SYSVSHM:-1}" = 0 ] && rm -f $CONF/20-sysvshm.ini || ln -sf $MODS/sysvshm.ini $CONF/20-sysvshm.ini
	[ \( "${PHP_MODULE_TIDEWAYS:-1}" = 0 -a -z "${PHP_CLI_MODULE_TIDEWAYS}" \) -o "${PHP_CLI_MODULE_TIDEWAYS:-1}" = 0 ] && rm -f $CONF/20-tideways.ini || ln -sf $MODS/tideways.ini $CONF/20-tideways.ini
	[ \( "${PHP_MODULE_TIDY:-1}" = 0 -a -z "${PHP_CLI_MODULE_TIDY}" \) -o "${PHP_CLI_MODULE_TIDY:-1}" = 0 ] && rm -f $CONF/20-tidy.ini || ln -sf $MODS/tidy.ini $CONF/20-tidy.ini
	[ \( "${PHP_MODULE_TOKENIZER:-1}" = 0 -a -z "${PHP_CLI_MODULE_TOKENIZER}" \) -o "${PHP_CLI_MODULE_TOKENIZER:-1}" = 0 ] && rm -f $CONF/20-tokenizer.ini || ln -sf $MODS/tokenizer.ini $CONF/20-tokenizer.ini
	[ \( "${PHP_MODULE_UOPZ:-1}" = 0 -a -z "${PHP_CLI_MODULE_UOPZ}" \) -o "${PHP_CLI_MODULE_UOPZ:-1}" = 0 ] && rm -f $CONF/20-uopz.ini || ln -sf $MODS/uopz.ini $CONF/20-uopz.ini
	[ \( "${PHP_MODULE_UPLOADPROGRESS:-1}" = 0 -a -z "${PHP_CLI_MODULE_UPLOADPROGRESS}" \) -o "${PHP_CLI_MODULE_UPLOADPROGRESS:-1}" = 0 ] && rm -f $CONF/20-uploadprogress.ini || ln -sf $MODS/uploadprogress.ini $CONF/20-uploadprogress.ini
	[ \( "${PHP_MODULE_UUID:-1}" = 0 -a -z "${PHP_CLI_MODULE_UUID}" \) -o "${PHP_CLI_MODULE_UUID:-1}" = 0 ] && rm -f $CONF/20-uuid.ini || ln -sf $MODS/uuid.ini $CONF/20-uuid.ini
	[ \( "${PHP_MODULE_VIPS:-1}" = 0 -a -z "${PHP_CLI_MODULE_VIPS}" \) -o "${PHP_CLI_MODULE_VIPS:-1}" = 0 ] && rm -f $CONF/30-vips.ini || ln -sf $MODS/vips.ini $CONF/30-vips.ini
	[ \( "${PHP_MODULE_XDEBUG:-1}" = 0 -a -z "${PHP_CLI_MODULE_XDEBUG}" \) -o "${PHP_CLI_MODULE_XDEBUG:-1}" = 0 ] && rm -f $CONF/20-xdebug.ini || ln -sf $MODS/xdebug.ini $CONF/20-xdebug.ini
	[ \( "${PHP_MODULE_XHPROF:-1}" = 0 -a -z "${PHP_CLI_MODULE_XHPROF}" \) -o "${PHP_CLI_MODULE_XHPROF:-1}" = 0 ] && rm -f $CONF/20-xhprof.ini || ln -sf $MODS/xhprof.ini $CONF/20-xhprof.ini
	[ \( "${PHP_MODULE_XML:-1}" = 0 -a -z "${PHP_CLI_MODULE_XML}" \) -o "${PHP_CLI_MODULE_XML:-1}" = 0 ] && rm -f $CONF/15-xml.ini || ln -sf $MODS/xml.ini $CONF/15-xml.ini
	[ \( "${PHP_MODULE_XMLREADER:-1}" = 0 -a -z "${PHP_CLI_MODULE_XMLREADER}" \) -o "${PHP_CLI_MODULE_XMLREADER:-1}" = 0 ] && rm -f $CONF/20-xmlreader.ini || ln -sf $MODS/xmlreader.ini $CONF/20-xmlreader.ini
	[ \( "${PHP_MODULE_XMLRPC:-1}" = 0 -a -z "${PHP_CLI_MODULE_XMLRPC}" \) -o "${PHP_CLI_MODULE_XMLRPC:-1}" = 0 ] && rm -f $CONF/20-xmlrpc.ini || ln -sf $MODS/xmlrpc.ini $CONF/20-xmlrpc.ini
	[ \( "${PHP_MODULE_XMLWRITER:-1}" = 0 -a -z "${PHP_CLI_MODULE_XMLWRITER}" \) -o "${PHP_CLI_MODULE_XMLWRITER:-1}" = 0 ] && rm -f $CONF/20-xmlwriter.ini || ln -sf $MODS/xmlwriter.ini $CONF/20-xmlwriter.ini
	[ \( "${PHP_MODULE_XSL:-1}" = 0 -a -z "${PHP_CLI_MODULE_XSL}" \) -o "${PHP_CLI_MODULE_XSL:-1}" = 0 ] && rm -f $CONF/20-xsl.ini || ln -sf $MODS/xsl.ini $CONF/20-xsl.ini
	[ \( "${PHP_MODULE_YAC:-1}" = 0 -a -z "${PHP_CLI_MODULE_YAC}" \) -o "${PHP_CLI_MODULE_YAC:-1}" = 0 ] && rm -f $CONF/20-yac.ini || ln -sf $MODS/yac.ini $CONF/20-yac.ini
	[ \( "${PHP_MODULE_YAML:-1}" = 0 -a -z "${PHP_CLI_MODULE_YAML}" \) -o "${PHP_CLI_MODULE_YAML:-1}" = 0 ] && rm -f $CONF/20-yaml.ini || ln -sf $MODS/yaml.ini $CONF/20-yaml.ini
	[ \( "${PHP_MODULE_ZIP:-1}" = 0 -a -z "${PHP_CLI_MODULE_ZIP}" \) -o "${PHP_CLI_MODULE_ZIP:-1}" = 0 ] && rm -f $CONF/20-zip.ini || ln -sf $MODS/zip.ini $CONF/20-zip.ini
	[ \( "${PHP_MODULE_ZMQ:-1}" = 0 -a -z "${PHP_CLI_MODULE_ZMQ}" \) -o "${PHP_CLI_MODULE_ZMQ:-1}" = 0 ] && rm -f $CONF/20-zmq.ini || ln -sf $MODS/zmq.ini $CONF/20-zmq.ini
	[ \( "${PHP_MODULE_ZSTD:-1}" = 0 -a -z "${PHP_CLI_MODULE_ZSTD}" \) -o "${PHP_CLI_MODULE_ZSTD:-1}" = 0 ] && rm -f $CONF/30-zstd.ini || ln -sf $MODS/zstd.ini $CONF/30-zstd.ini
else
	[ \( "${PHP_MODULE_AMQP:-0}" != 0 -a -z "${PHP_CLI_MODULE_AMQP}" \) -o "${PHP_CLI_MODULE_AMQP:-0}" != 0 ] && ln -sf $MODS/amqp.ini $CONF/20-amqp.ini || rm -f $CONF/20-amqp.ini
	[ \( "${PHP_MODULE_APCU:-0}" != 0 -a -z "${PHP_CLI_MODULE_APCU}" \) -o "${PHP_CLI_MODULE_APCU:-0}" != 0 ] && ln -sf $MODS/apcu.ini $CONF/20-apcu.ini || rm -f $CONF/20-apcu.ini
	[ \( "${PHP_MODULE_AST:-0}" != 0 -a -z "${PHP_CLI_MODULE_AST}" \) -o "${PHP_CLI_MODULE_AST:-0}" != 0 ] && ln -sf $MODS/ast.ini $CONF/20-ast.ini || rm -f $CONF/20-ast.ini
	[ \( "${PHP_MODULE_BCMATH:-0}" != 0 -a -z "${PHP_CLI_MODULE_BCMATH}" \) -o "${PHP_CLI_MODULE_BCMATH:-0}" != 0 ] && ln -sf $MODS/bcmath.ini $CONF/20-bcmath.ini || rm -f $CONF/20-bcmath.ini
	[ \( "${PHP_MODULE_BZ2:-0}" != 0 -a -z "${PHP_CLI_MODULE_BZ2}" \) -o "${PHP_CLI_MODULE_BZ2:-0}" != 0 ] && ln -sf $MODS/bz2.ini $CONF/20-bz2.ini || rm -f $CONF/20-bz2.ini
	[ \( "${PHP_MODULE_CALENDAR:-0}" != 0 -a -z "${PHP_CLI_MODULE_CALENDAR}" \) -o "${PHP_CLI_MODULE_CALENDAR:-0}" != 0 ] && ln -sf $MODS/calendar.ini $CONF/20-calendar.ini || rm -f $CONF/20-calendar.ini
	[ \( "${PHP_MODULE_CTYPE:-0}" != 0 -a -z "${PHP_CLI_MODULE_CTYPE}" \) -o "${PHP_CLI_MODULE_CTYPE:-0}" != 0 ] && ln -sf $MODS/ctype.ini $CONF/20-ctype.ini || rm -f $CONF/20-ctype.ini
	[ \( "${PHP_MODULE_CURL:-0}" != 0 -a -z "${PHP_CLI_MODULE_CURL}" \) -o "${PHP_CLI_MODULE_CURL:-0}" != 0 ] && ln -sf $MODS/curl.ini $CONF/20-curl.ini || rm -f $CONF/20-curl.ini
	[ \( "${PHP_MODULE_DBA:-0}" != 0 -a -z "${PHP_CLI_MODULE_DBA}" \) -o "${PHP_CLI_MODULE_DBA:-0}" != 0 ] && ln -sf $MODS/dba.ini $CONF/20-dba.ini || rm -f $CONF/20-dba.ini
	[ \( "${PHP_MODULE_DECIMAL:-0}" != 0 -a -z "${PHP_CLI_MODULE_DECIMAL}" \) -o "${PHP_CLI_MODULE_DECIMAL:-0}" != 0 ] && ln -sf $MODS/decimal.ini $CONF/30-decimal.ini || rm -f $CONF/30-decimal.ini
	[ \( "${PHP_MODULE_DIO:-0}" != 0 -a -z "${PHP_CLI_MODULE_DIO}" \) -o "${PHP_CLI_MODULE_DIO:-0}" != 0 ] && ln -sf $MODS/dio.ini $CONF/20-dio.ini || rm -f $CONF/20-dio.ini
	[ \( "${PHP_MODULE_DOM:-0}" != 0 -a -z "${PHP_CLI_MODULE_DOM}" \) -o "${PHP_CLI_MODULE_DOM:-0}" != 0 ] && ln -sf $MODS/dom.ini $CONF/20-dom.ini || rm -f $CONF/20-dom.ini
	[ \( "${PHP_MODULE_DS:-0}" != 0 -a -z "${PHP_CLI_MODULE_DS}" \) -o "${PHP_CLI_MODULE_DS:-0}" != 0 ] && ln -sf $MODS/ds.ini $CONF/30-ds.ini || rm -f $CONF/30-ds.ini
	[ \( "${PHP_MODULE_ENCHANT:-0}" != 0 -a -z "${PHP_CLI_MODULE_ENCHANT}" \) -o "${PHP_CLI_MODULE_ENCHANT:-0}" != 0 ] && ln -sf $MODS/enchant.ini $CONF/20-enchant.ini || rm -f $CONF/20-enchant.ini
	[ \( "${PHP_MODULE_EXCIMER:-0}" != 0 -a -z "${PHP_CLI_MODULE_EXCIMER}" \) -o "${PHP_CLI_MODULE_EXCIMER:-0}" != 0 ] && ln -sf $MODS/excimer.ini $CONF/20-excimer.ini || rm -f $CONF/20-excimer.ini
	[ \( "${PHP_MODULE_EXIF:-0}" != 0 -a -z "${PHP_CLI_MODULE_EXIF}" \) -o "${PHP_CLI_MODULE_EXIF:-0}" != 0 ] && ln -sf $MODS/exif.ini $CONF/20-exif.ini || rm -f $CONF/20-exif.ini
	[ \( "${PHP_MODULE_FFI:-0}" != 0 -a -z "${PHP_CLI_MODULE_FFI}" \) -o "${PHP_CLI_MODULE_FFI:-0}" != 0 ] && ln -sf $MODS/ffi.ini $CONF/20-ffi.ini || rm -f $CONF/20-ffi.ini
	[ \( "${PHP_MODULE_FILEINFO:-0}" != 0 -a -z "${PHP_CLI_MODULE_FILEINFO}" \) -o "${PHP_CLI_MODULE_FILEINFO:-0}" != 0 ] && ln -sf $MODS/fileinfo.ini $CONF/20-fileinfo.ini || rm -f $CONF/20-fileinfo.ini
	[ \( "${PHP_MODULE_FTP:-0}" != 0 -a -z "${PHP_CLI_MODULE_FTP}" \) -o "${PHP_CLI_MODULE_FTP:-0}" != 0 ] && ln -sf $MODS/ftp.ini $CONF/20-ftp.ini || rm -f $CONF/20-ftp.ini
	[ \( "${PHP_MODULE_GD:-0}" != 0 -a -z "${PHP_CLI_MODULE_GD}" \) -o "${PHP_CLI_MODULE_GD:-0}" != 0 ] && ln -sf $MODS/gd.ini $CONF/20-gd.ini || rm -f $CONF/20-gd.ini
	[ \( "${PHP_MODULE_GEARMAN:-0}" != 0 -a -z "${PHP_CLI_MODULE_GEARMAN}" \) -o "${PHP_CLI_MODULE_GEARMAN:-0}" != 0 ] && ln -sf $MODS/gearman.ini $CONF/20-gearman.ini || rm -f $CONF/20-gearman.ini
	[ \( "${PHP_MODULE_GETTEXT:-0}" != 0 -a -z "${PHP_CLI_MODULE_GETTEXT}" \) -o "${PHP_CLI_MODULE_GETTEXT:-0}" != 0 ] && ln -sf $MODS/gettext.ini $CONF/20-gettext.ini || rm -f $CONF/20-gettext.ini
	[ \( "${PHP_MODULE_GMAGICK:-0}" != 0 -a -z "${PHP_CLI_MODULE_GMAGICK}" \) -o "${PHP_CLI_MODULE_GMAGICK:-0}" != 0 ] && ln -sf $MODS/gmagick.ini $CONF/20-gmagick.ini || rm -f $CONF/20-gmagick.ini
	[ \( "${PHP_MODULE_GMP:-0}" != 0 -a -z "${PHP_CLI_MODULE_GMP}" \) -o "${PHP_CLI_MODULE_GMP:-0}" != 0 ] && ln -sf $MODS/gmp.ini $CONF/20-gmp.ini || rm -f $CONF/20-gmp.ini
	[ \( "${PHP_MODULE_GNUPG:-0}" != 0 -a -z "${PHP_CLI_MODULE_GNUPG}" \) -o "${PHP_CLI_MODULE_GNUPG:-0}" != 0 ] && ln -sf $MODS/gnupg.ini $CONF/20-gnupg.ini || rm -f $CONF/20-gnupg.ini
	[ \( "${PHP_MODULE_GRPC:-0}" != 0 -a -z "${PHP_CLI_MODULE_GRPC}" \) -o "${PHP_CLI_MODULE_GRPC:-0}" != 0 ] && ln -sf $MODS/grpc.ini $CONF/30-grpc.ini || rm -f $CONF/30-grpc.ini
	[ \( "${PHP_MODULE_HTTP:-0}" != 0 -a -z "${PHP_CLI_MODULE_HTTP}" \) -o "${PHP_CLI_MODULE_HTTP:-0}" != 0 ] && ln -sf $MODS/http.ini $CONF/25-http.ini || rm -f $CONF/25-http.ini
	[ \( "${PHP_MODULE_ICONV:-0}" != 0 -a -z "${PHP_CLI_MODULE_ICONV}" \) -o "${PHP_CLI_MODULE_ICONV:-0}" != 0 ] && ln -sf $MODS/iconv.ini $CONF/20-iconv.ini || rm -f $CONF/20-iconv.ini
	[ \( "${PHP_MODULE_IGBINARY:-0}" != 0 -a -z "${PHP_CLI_MODULE_IGBINARY}" \) -o "${PHP_CLI_MODULE_IGBINARY:-0}" != 0 ] && ln -sf $MODS/igbinary.ini $CONF/20-igbinary.ini || rm -f $CONF/20-igbinary.ini
	[ \( "${PHP_MODULE_IMAGICK:-0}" != 0 -a -z "${PHP_CLI_MODULE_IMAGICK}" \) -o "${PHP_CLI_MODULE_IMAGICK:-0}" != 0 ] && ln -sf $MODS/imagick.ini $CONF/20-imagick.ini || rm -f $CONF/20-imagick.ini
	[ \( "${PHP_MODULE_IMAP:-0}" != 0 -a -z "${PHP_CLI_MODULE_IMAP}" \) -o "${PHP_CLI_MODULE_IMAP:-0}" != 0 ] && ln -sf $MODS/imap.ini $CONF/20-imap.ini || rm -f $CONF/20-imap.ini
	[ \( "${PHP_MODULE_INOTIFY:-0}" != 0 -a -z "${PHP_CLI_MODULE_INOTIFY}" \) -o "${PHP_CLI_MODULE_INOTIFY:-0}" != 0 ] && ln -sf $MODS/inotify.ini $CONF/30-inotify.ini || rm -f $CONF/30-inotify.ini
	[ \( "${PHP_MODULE_INTL:-0}" != 0 -a -z "${PHP_CLI_MODULE_INTL}" \) -o "${PHP_CLI_MODULE_INTL:-0}" != 0 ] && ln -sf $MODS/intl.ini $CONF/20-intl.ini || rm -f $CONF/20-intl.ini
	[ \( "${PHP_MODULE_LDAP:-0}" != 0 -a -z "${PHP_CLI_MODULE_LDAP}" \) -o "${PHP_CLI_MODULE_LDAP:-0}" != 0 ] && ln -sf $MODS/ldap.ini $CONF/20-ldap.ini || rm -f $CONF/20-ldap.ini
	[ \( "${PHP_MODULE_LIBVIRT_PHP:-0}" != 0 -a -z "${PHP_CLI_MODULE_LIBVIRT_PHP}" \) -o "${PHP_CLI_MODULE_LIBVIRT_PHP:-0}" != 0 ] && ln -sf $MODS/libvirt-php.ini $CONF/40-libvirt-php.ini || rm -f $CONF/40-libvirt-php.ini
	[ \( "${PHP_MODULE_LZ4:-0}" != 0 -a -z "${PHP_CLI_MODULE_LZ4}" \) -o "${PHP_CLI_MODULE_LZ4:-0}" != 0 ] && ln -sf $MODS/lz4.ini $CONF/20-lz4.ini || rm -f $CONF/20-lz4.ini
	[ \( "${PHP_MODULE_MAILPARSE:-0}" != 0 -a -z "${PHP_CLI_MODULE_MAILPARSE}" \) -o "${PHP_CLI_MODULE_MAILPARSE:-0}" != 0 ] && ln -sf $MODS/mailparse.ini $CONF/25-mailparse.ini || rm -f $CONF/25-mailparse.ini
	[ \( "${PHP_MODULE_MAXMINDDB:-0}" != 0 -a -z "${PHP_CLI_MODULE_MAXMINDDB}" \) -o "${PHP_CLI_MODULE_MAXMINDDB:-0}" != 0 ] && ln -sf $MODS/maxminddb.ini $CONF/30-maxminddb.ini || rm -f $CONF/30-maxminddb.ini
	[ \( "${PHP_MODULE_MBSTRING:-0}" != 0 -a -z "${PHP_CLI_MODULE_MBSTRING}" \) -o "${PHP_CLI_MODULE_MBSTRING:-0}" != 0 ] && ln -sf $MODS/mbstring.ini $CONF/20-mbstring.ini || rm -f $CONF/20-mbstring.ini
	[ \( "${PHP_MODULE_MCRYPT:-0}" != 0 -a -z "${PHP_CLI_MODULE_MCRYPT}" \) -o "${PHP_CLI_MODULE_MCRYPT:-0}" != 0 ] && ln -sf $MODS/mcrypt.ini $CONF/20-mcrypt.ini || rm -f $CONF/20-mcrypt.ini
	[ \( "${PHP_MODULE_MEMCACHE:-0}" != 0 -a -z "${PHP_CLI_MODULE_MEMCACHE}" \) -o "${PHP_CLI_MODULE_MEMCACHE:-0}" != 0 ] && ln -sf $MODS/memcache.ini $CONF/20-memcache.ini || rm -f $CONF/20-memcache.ini
	[ \( "${PHP_MODULE_MEMCACHED:-0}" != 0 -a -z "${PHP_CLI_MODULE_MEMCACHED}" \) -o "${PHP_CLI_MODULE_MEMCACHED:-0}" != 0 ] && ln -sf $MODS/memcached.ini $CONF/25-memcached.ini || rm -f $CONF/25-memcached.ini
	[ \( "${PHP_MODULE_MONGODB:-0}" != 0 -a -z "${PHP_CLI_MODULE_MONGODB}" \) -o "${PHP_CLI_MODULE_MONGODB:-0}" != 0 ] && ln -sf $MODS/mongodb.ini $CONF/20-mongodb.ini || rm -f $CONF/20-mongodb.ini
	[ \( "${PHP_MODULE_MSGPACK:-0}" != 0 -a -z "${PHP_CLI_MODULE_MSGPACK}" \) -o "${PHP_CLI_MODULE_MSGPACK:-0}" != 0 ] && ln -sf $MODS/msgpack.ini $CONF/20-msgpack.ini || rm -f $CONF/20-msgpack.ini
	[ \( "${PHP_MODULE_MYSQLI:-0}" != 0 -a -z "${PHP_CLI_MODULE_MYSQLI}" \) -o "${PHP_CLI_MODULE_MYSQLI:-0}" != 0 ] && ln -sf $MODS/mysqli.ini $CONF/20-mysqli.ini || rm -f $CONF/20-mysqli.ini
	[ \( "${PHP_MODULE_MYSQLND:-0}" != 0 -a -z "${PHP_CLI_MODULE_MYSQLND}" \) -o "${PHP_CLI_MODULE_MYSQLND:-0}" != 0 ] && ln -sf $MODS/mysqlnd.ini $CONF/10-mysqlnd.ini || rm -f $CONF/10-mysqlnd.ini
	[ \( "${PHP_MODULE_OAUTH:-0}" != 0 -a -z "${PHP_CLI_MODULE_OAUTH}" \) -o "${PHP_CLI_MODULE_OAUTH:-0}" != 0 ] && ln -sf $MODS/oauth.ini $CONF/20-oauth.ini || rm -f $CONF/20-oauth.ini
	[ \( "${PHP_MODULE_ODBC:-0}" != 0 -a -z "${PHP_CLI_MODULE_ODBC}" \) -o "${PHP_CLI_MODULE_ODBC:-0}" != 0 ] && ln -sf $MODS/odbc.ini $CONF/20-odbc.ini || rm -f $CONF/20-odbc.ini
	[ \( "${PHP_MODULE_OPCACHE:-0}" != 0 -a -z "${PHP_CLI_MODULE_OPCACHE}" \) -o "${PHP_CLI_MODULE_OPCACHE:-0}" != 0 ] && ln -sf $MODS/opcache.ini $CONF/10-opcache.ini || rm -f $CONF/10-opcache.ini
	[ \( "${PHP_MODULE_OPENTELEMETRY:-0}" != 0 -a -z "${PHP_CLI_MODULE_OPENTELEMETRY}" \) -o "${PHP_CLI_MODULE_OPENTELEMETRY:-0}" != 0 ] && ln -sf $MODS/opentelemetry.ini $CONF/20-opentelemetry.ini || rm -f $CONF/20-opentelemetry.ini
	[ \( "${PHP_MODULE_PCOV:-0}" != 0 -a -z "${PHP_CLI_MODULE_PCOV}" \) -o "${PHP_CLI_MODULE_PCOV:-0}" != 0 ] && ln -sf $MODS/pcov.ini $CONF/20-pcov.ini || rm -f $CONF/20-pcov.ini
	[ \( "${PHP_MODULE_PDO:-0}" != 0 -a -z "${PHP_CLI_MODULE_PDO}" \) -o "${PHP_CLI_MODULE_PDO:-0}" != 0 ] && ln -sf $MODS/pdo.ini $CONF/10-pdo.ini || rm -f $CONF/10-pdo.ini
	[ \( "${PHP_MODULE_PDO_DBLIB:-0}" != 0 -a -z "${PHP_CLI_MODULE_PDO_DBLIB}" \) -o "${PHP_CLI_MODULE_PDO_DBLIB:-0}" != 0 ] && ln -sf $MODS/pdo_dblib.ini $CONF/20-pdo_dblib.ini || rm -f $CONF/20-pdo_dblib.ini
	[ \( "${PHP_MODULE_PDO_FIREBIRD:-0}" != 0 -a -z "${PHP_CLI_MODULE_PDO_FIREBIRD}" \) -o "${PHP_CLI_MODULE_PDO_FIREBIRD:-0}" != 0 ] && ln -sf $MODS/pdo_firebird.ini $CONF/20-pdo_firebird.ini || rm -f $CONF/20-pdo_firebird.ini
	[ \( "${PHP_MODULE_PDO_MYSQL:-0}" != 0 -a -z "${PHP_CLI_MODULE_PDO_MYSQL}" \) -o "${PHP_CLI_MODULE_PDO_MYSQL:-0}" != 0 ] && ln -sf $MODS/pdo_mysql.ini $CONF/20-pdo_mysql.ini || rm -f $CONF/20-pdo_mysql.ini
	[ \( "${PHP_MODULE_PDO_ODBC:-0}" != 0 -a -z "${PHP_CLI_MODULE_PDO_ODBC}" \) -o "${PHP_CLI_MODULE_PDO_ODBC:-0}" != 0 ] && ln -sf $MODS/pdo_odbc.ini $CONF/20-pdo_odbc.ini || rm -f $CONF/20-pdo_odbc.ini
	[ \( "${PHP_MODULE_PDO_PGSQL:-0}" != 0 -a -z "${PHP_CLI_MODULE_PDO_PGSQL}" \) -o "${PHP_CLI_MODULE_PDO_PGSQL:-0}" != 0 ] && ln -sf $MODS/pdo_pgsql.ini $CONF/20-pdo_pgsql.ini || rm -f $CONF/20-pdo_pgsql.ini
	[ \( "${PHP_MODULE_PDO_SQLITE:-0}" != 0 -a -z "${PHP_CLI_MODULE_PDO_SQLITE}" \) -o "${PHP_CLI_MODULE_PDO_SQLITE:-0}" != 0 ] && ln -sf $MODS/pdo_sqlite.ini $CONF/20-pdo_sqlite.ini || rm -f $CONF/20-pdo_sqlite.ini
	[ \( "${PHP_MODULE_PGSQL:-0}" != 0 -a -z "${PHP_CLI_MODULE_PGSQL}" \) -o "${PHP_CLI_MODULE_PGSQL:-0}" != 0 ] && ln -sf $MODS/pgsql.ini $CONF/20-pgsql.ini || rm -f $CONF/20-pgsql.ini
	[ \( "${PHP_MODULE_PHALCON:-0}" != 0 -a -z "${PHP_CLI_MODULE_PHALCON}" \) -o "${PHP_CLI_MODULE_PHALCON:-0}" != 0 ] && ln -sf $MODS/phalcon.ini $CONF/35-phalcon.ini || rm -f $CONF/35-phalcon.ini
	[ \( "${PHP_MODULE_PHAR:-0}" != 0 -a -z "${PHP_CLI_MODULE_PHAR}" \) -o "${PHP_CLI_MODULE_PHAR:-0}" != 0 ] && ln -sf $MODS/phar.ini $CONF/20-phar.ini || rm -f $CONF/20-phar.ini
	[ \( "${PHP_MODULE_PINBA:-0}" != 0 -a -z "${PHP_CLI_MODULE_PINBA}" \) -o "${PHP_CLI_MODULE_PINBA:-0}" != 0 ] && ln -sf $MODS/pinba.ini $CONF/20-pinba.ini || rm -f $CONF/20-pinba.ini
	[ \( "${PHP_MODULE_POSIX:-0}" != 0 -a -z "${PHP_CLI_MODULE_POSIX}" \) -o "${PHP_CLI_MODULE_POSIX:-0}" != 0 ] && ln -sf $MODS/posix.ini $CONF/20-posix.ini || rm -f $CONF/20-posix.ini
	[ \( "${PHP_MODULE_PQ:-0}" != 0 -a -z "${PHP_CLI_MODULE_PQ}" \) -o "${PHP_CLI_MODULE_PQ:-0}" != 0 ] && ln -sf $MODS/pq.ini $CONF/25-pq.ini || rm -f $CONF/25-pq.ini
	[ \( "${PHP_MODULE_PROPRO:-0}" != 0 -a -z "${PHP_CLI_MODULE_PROPRO}" \) -o "${PHP_CLI_MODULE_PROPRO:-0}" != 0 ] && ln -sf $MODS/propro.ini $CONF/20-propro.ini || rm -f $CONF/20-propro.ini
	[ \( "${PHP_MODULE_PROTOBUF:-0}" != 0 -a -z "${PHP_CLI_MODULE_PROTOBUF}" \) -o "${PHP_CLI_MODULE_PROTOBUF:-0}" != 0 ] && ln -sf $MODS/protobuf.ini $CONF/30-protobuf.ini || rm -f $CONF/30-protobuf.ini
	[ \( "${PHP_MODULE_PS:-0}" != 0 -a -z "${PHP_CLI_MODULE_PS}" \) -o "${PHP_CLI_MODULE_PS:-0}" != 0 ] && ln -sf $MODS/ps.ini $CONF/20-ps.ini || rm -f $CONF/20-ps.ini
	[ \( "${PHP_MODULE_PSPELL:-0}" != 0 -a -z "${PHP_CLI_MODULE_PSPELL}" \) -o "${PHP_CLI_MODULE_PSPELL:-0}" != 0 ] && ln -sf $MODS/pspell.ini $CONF/20-pspell.ini || rm -f $CONF/20-pspell.ini
	[ \( "${PHP_MODULE_PSR:-0}" != 0 -a -z "${PHP_CLI_MODULE_PSR}" \) -o "${PHP_CLI_MODULE_PSR:-0}" != 0 ] && ln -sf $MODS/psr.ini $CONF/15-psr.ini || rm -f $CONF/15-psr.ini
	[ \( "${PHP_MODULE_RAPHF:-0}" != 0 -a -z "${PHP_CLI_MODULE_RAPHF}" \) -o "${PHP_CLI_MODULE_RAPHF:-0}" != 0 ] && ln -sf $MODS/raphf.ini $CONF/20-raphf.ini || rm -f $CONF/20-raphf.ini
	[ \( "${PHP_MODULE_RDKAFKA:-0}" != 0 -a -z "${PHP_CLI_MODULE_RDKAFKA}" \) -o "${PHP_CLI_MODULE_RDKAFKA:-0}" != 0 ] && ln -sf $MODS/rdkafka.ini $CONF/30-rdkafka.ini || rm -f $CONF/30-rdkafka.ini
	[ \( "${PHP_MODULE_READLINE:-0}" != 0 -a -z "${PHP_CLI_MODULE_READLINE}" \) -o "${PHP_CLI_MODULE_READLINE:-0}" != 0 ] && ln -sf $MODS/readline.ini $CONF/20-readline.ini || rm -f $CONF/20-readline.ini
	[ \( "${PHP_MODULE_REDIS:-0}" != 0 -a -z "${PHP_CLI_MODULE_REDIS}" \) -o "${PHP_CLI_MODULE_REDIS:-0}" != 0 ] && ln -sf $MODS/redis.ini $CONF/25-redis.ini || rm -f $CONF/25-redis.ini
	[ \( "${PHP_MODULE_RRD:-0}" != 0 -a -z "${PHP_CLI_MODULE_RRD}" \) -o "${PHP_CLI_MODULE_RRD:-0}" != 0 ] && ln -sf $MODS/rrd.ini $CONF/20-rrd.ini || rm -f $CONF/20-rrd.ini
	[ \( "${PHP_MODULE_SHMOP:-0}" != 0 -a -z "${PHP_CLI_MODULE_SHMOP}" \) -o "${PHP_CLI_MODULE_SHMOP:-0}" != 0 ] && ln -sf $MODS/shmop.ini $CONF/20-shmop.ini || rm -f $CONF/20-shmop.ini
	[ \( "${PHP_MODULE_SIMPLEXML:-0}" != 0 -a -z "${PHP_CLI_MODULE_SIMPLEXML}" \) -o "${PHP_CLI_MODULE_SIMPLEXML:-0}" != 0 ] && ln -sf $MODS/simplexml.ini $CONF/20-simplexml.ini || rm -f $CONF/20-simplexml.ini
	[ \( "${PHP_MODULE_SMBCLIENT:-0}" != 0 -a -z "${PHP_CLI_MODULE_SMBCLIENT}" \) -o "${PHP_CLI_MODULE_SMBCLIENT:-0}" != 0 ] && ln -sf $MODS/smbclient.ini $CONF/20-smbclient.ini || rm -f $CONF/20-smbclient.ini
	[ \( "${PHP_MODULE_SNMP:-0}" != 0 -a -z "${PHP_CLI_MODULE_SNMP}" \) -o "${PHP_CLI_MODULE_SNMP:-0}" != 0 ] && ln -sf $MODS/snmp.ini $CONF/20-snmp.ini || rm -f $CONF/20-snmp.ini
	[ \( "${PHP_MODULE_SOAP:-0}" != 0 -a -z "${PHP_CLI_MODULE_SOAP}" \) -o "${PHP_CLI_MODULE_SOAP:-0}" != 0 ] && ln -sf $MODS/soap.ini $CONF/20-soap.ini || rm -f $CONF/20-soap.ini
	[ \( "${PHP_MODULE_SOCKETS:-0}" != 0 -a -z "${PHP_CLI_MODULE_SOCKETS}" \) -o "${PHP_CLI_MODULE_SOCKETS:-0}" != 0 ] && ln -sf $MODS/sockets.ini $CONF/20-sockets.ini || rm -f $CONF/20-sockets.ini
	[ \( "${PHP_MODULE_SOLR:-0}" != 0 -a -z "${PHP_CLI_MODULE_SOLR}" \) -o "${PHP_CLI_MODULE_SOLR:-0}" != 0 ] && ln -sf $MODS/solr.ini $CONF/20-solr.ini || rm -f $CONF/20-solr.ini
	[ \( "${PHP_MODULE_SQLITE3:-0}" != 0 -a -z "${PHP_CLI_MODULE_SQLITE3}" \) -o "${PHP_CLI_MODULE_SQLITE3:-0}" != 0 ] && ln -sf $MODS/sqlite3.ini $CONF/20-sqlite3.ini || rm -f $CONF/20-sqlite3.ini
	[ \( "${PHP_MODULE_SSH2:-0}" != 0 -a -z "${PHP_CLI_MODULE_SSH2}" \) -o "${PHP_CLI_MODULE_SSH2:-0}" != 0 ] && ln -sf $MODS/ssh2.ini $CONF/20-ssh2.ini || rm -f $CONF/20-ssh2.ini
	[ \( "${PHP_MODULE_STOMP:-0}" != 0 -a -z "${PHP_CLI_MODULE_STOMP}" \) -o "${PHP_CLI_MODULE_STOMP:-0}" != 0 ] && ln -sf $MODS/stomp.ini $CONF/20-stomp.ini || rm -f $CONF/20-stomp.ini
	[ \( "${PHP_MODULE_SWOOLE:-0}" != 0 -a -z "${PHP_CLI_MODULE_SWOOLE}" \) -o "${PHP_CLI_MODULE_SWOOLE:-0}" != 0 ] && ln -sf $MODS/swoole.ini $CONF/25-swoole.ini || rm -f $CONF/25-swoole.ini
	[ \( "${PHP_MODULE_SYSVMSG:-0}" != 0 -a -z "${PHP_CLI_MODULE_SYSVMSG}" \) -o "${PHP_CLI_MODULE_SYSVMSG:-0}" != 0 ] && ln -sf $MODS/sysvmsg.ini $CONF/20-sysvmsg.ini || rm -f $CONF/20-sysvmsg.ini
	[ \( "${PHP_MODULE_SYSVSEM:-0}" != 0 -a -z "${PHP_CLI_MODULE_SYSVSEM}" \) -o "${PHP_CLI_MODULE_SYSVSEM:-0}" != 0 ] && ln -sf $MODS/sysvsem.ini $CONF/20-sysvsem.ini || rm -f $CONF/20-sysvsem.ini
	[ \( "${PHP_MODULE_SYSVSHM:-0}" != 0 -a -z "${PHP_CLI_MODULE_SYSVSHM}" \) -o "${PHP_CLI_MODULE_SYSVSHM:-0}" != 0 ] && ln -sf $MODS/sysvshm.ini $CONF/20-sysvshm.ini || rm -f $CONF/20-sysvshm.ini
	[ \( "${PHP_MODULE_TIDEWAYS:-0}" != 0 -a -z "${PHP_CLI_MODULE_TIDEWAYS}" \) -o "${PHP_CLI_MODULE_TIDEWAYS:-0}" != 0 ] && ln -sf $MODS/tideways.ini $CONF/20-tideways.ini || rm -f $CONF/20-tideways.ini
	[ \( "${PHP_MODULE_TIDY:-0}" != 0 -a -z "${PHP_CLI_MODULE_TIDY}" \) -o "${PHP_CLI_MODULE_TIDY:-0}" != 0 ] && ln -sf $MODS/tidy.ini $CONF/20-tidy.ini || rm -f $CONF/20-tidy.ini
	[ \( "${PHP_MODULE_TOKENIZER:-0}" != 0 -a -z "${PHP_CLI_MODULE_TOKENIZER}" \) -o "${PHP_CLI_MODULE_TOKENIZER:-0}" != 0 ] && ln -sf $MODS/tokenizer.ini $CONF/20-tokenizer.ini || rm -f $CONF/20-tokenizer.ini
	[ \( "${PHP_MODULE_UOPZ:-0}" != 0 -a -z "${PHP_CLI_MODULE_UOPZ}" \) -o "${PHP_CLI_MODULE_UOPZ:-0}" != 0 ] && ln -sf $MODS/uopz.ini $CONF/20-uopz.ini || rm -f $CONF/20-uopz.ini
	[ \( "${PHP_MODULE_UPLOADPROGRESS:-0}" != 0 -a -z "${PHP_CLI_MODULE_UPLOADPROGRESS}" \) -o "${PHP_CLI_MODULE_UPLOADPROGRESS:-0}" != 0 ] && ln -sf $MODS/uploadprogress.ini $CONF/20-uploadprogress.ini || rm -f $CONF/20-uploadprogress.ini
	[ \( "${PHP_MODULE_UUID:-0}" != 0 -a -z "${PHP_CLI_MODULE_UUID}" \) -o "${PHP_CLI_MODULE_UUID:-0}" != 0 ] && ln -sf $MODS/uuid.ini $CONF/20-uuid.ini || rm -f $CONF/20-uuid.ini
	[ \( "${PHP_MODULE_VIPS:-0}" != 0 -a -z "${PHP_CLI_MODULE_VIPS}" \) -o "${PHP_CLI_MODULE_VIPS:-0}" != 0 ] && ln -sf $MODS/vips.ini $CONF/30-vips.ini || rm -f $CONF/30-vips.ini
	[ \( "${PHP_MODULE_XDEBUG:-0}" != 0 -a -z "${PHP_CLI_MODULE_XDEBUG}" \) -o "${PHP_CLI_MODULE_XDEBUG:-0}" != 0 ] && ln -sf $MODS/xdebug.ini $CONF/20-xdebug.ini || rm -f $CONF/20-xdebug.ini
	[ \( "${PHP_MODULE_XHPROF:-0}" != 0 -a -z "${PHP_CLI_MODULE_XHPROF}" \) -o "${PHP_CLI_MODULE_XHPROF:-0}" != 0 ] && ln -sf $MODS/xhprof.ini $CONF/20-xhprof.ini || rm -f $CONF/20-xhprof.ini
	[ \( "${PHP_MODULE_XML:-0}" != 0 -a -z "${PHP_CLI_MODULE_XML}" \) -o "${PHP_CLI_MODULE_XML:-0}" != 0 ] && ln -sf $MODS/xml.ini $CONF/15-xml.ini || rm -f $CONF/15-xml.ini
	[ \( "${PHP_MODULE_XMLREADER:-0}" != 0 -a -z "${PHP_CLI_MODULE_XMLREADER}" \) -o "${PHP_CLI_MODULE_XMLREADER:-0}" != 0 ] && ln -sf $MODS/xmlreader.ini $CONF/20-xmlreader.ini || rm -f $CONF/20-xmlreader.ini
	[ \( "${PHP_MODULE_XMLRPC:-0}" != 0 -a -z "${PHP_CLI_MODULE_XMLRPC}" \) -o "${PHP_CLI_MODULE_XMLRPC:-0}" != 0 ] && ln -sf $MODS/xmlrpc.ini $CONF/20-xmlrpc.ini || rm -f $CONF/20-xmlrpc.ini
	[ \( "${PHP_MODULE_XMLWRITER:-0}" != 0 -a -z "${PHP_CLI_MODULE_XMLWRITER}" \) -o "${PHP_CLI_MODULE_XMLWRITER:-0}" != 0 ] && ln -sf $MODS/xmlwriter.ini $CONF/20-xmlwriter.ini || rm -f $CONF/20-xmlwriter.ini
	[ \( "${PHP_MODULE_XSL:-0}" != 0 -a -z "${PHP_CLI_MODULE_XSL}" \) -o "${PHP_CLI_MODULE_XSL:-0}" != 0 ] && ln -sf $MODS/xsl.ini $CONF/20-xsl.ini || rm -f $CONF/20-xsl.ini
	[ \( "${PHP_MODULE_YAC:-0}" != 0 -a -z "${PHP_CLI_MODULE_YAC}" \) -o "${PHP_CLI_MODULE_YAC:-0}" != 0 ] && ln -sf $MODS/yac.ini $CONF/20-yac.ini || rm -f $CONF/20-yac.ini
	[ \( "${PHP_MODULE_YAML:-0}" != 0 -a -z "${PHP_CLI_MODULE_YAML}" \) -o "${PHP_CLI_MODULE_YAML:-0}" != 0 ] && ln -sf $MODS/yaml.ini $CONF/20-yaml.ini || rm -f $CONF/20-yaml.ini
	[ \( "${PHP_MODULE_ZIP:-0}" != 0 -a -z "${PHP_CLI_MODULE_ZIP}" \) -o "${PHP_CLI_MODULE_ZIP:-0}" != 0 ] && ln -sf $MODS/zip.ini $CONF/20-zip.ini || rm -f $CONF/20-zip.ini
	[ \( "${PHP_MODULE_ZMQ:-0}" != 0 -a -z "${PHP_CLI_MODULE_ZMQ}" \) -o "${PHP_CLI_MODULE_ZMQ:-0}" != 0 ] && ln -sf $MODS/zmq.ini $CONF/20-zmq.ini || rm -f $CONF/20-zmq.ini
	[ \( "${PHP_MODULE_ZSTD:-0}" != 0 -a -z "${PHP_CLI_MODULE_ZSTD}" \) -o "${PHP_CLI_MODULE_ZSTD:-0}" != 0 ] && ln -sf $MODS/zstd.ini $CONF/30-zstd.ini || rm -f $CONF/30-zstd.ini
fi
